FROM node:slim

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Bundle app source
COPY ./calendar_service /usr/src/app/
COPY ./libs /usr/src/app/libs

# Install app dependencies
RUN npm install

EXPOSE 5502

RUN useradd -s /bin/bash -d /usr calendaruser
USER calendaruser

CMD ["npm", "start"]
