FROM node:slim

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Bundle app source
COPY ./synchronize_service /usr/src/app/
COPY ./libs /usr/src/app/libs

# Install app dependencies
#RUN npm i -g gulp
RUN npm install

EXPOSE 5500

RUN useradd -s /bin/bash -d /usr synchuser
USER synchuser

CMD ["npm", "start"]
#CMD ["gulp"]
